name: Access Output URL

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      # Notice: If NO value in `name`, url will not be displayed in output Job
      name: main # ${{ github.base_ref }} # No value on push?
      url: ${{ steps.generate_url.outputs.URL }}
  
    steps:
      - name: Generate and Outputs URL
        id: generate_url
        run: |
          echo "URL=https://lightzane.github.io/sky-events" >> $GITHUB_OUTPUT
