name: Conditional

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  selection:
    runs-on: ubuntu-latest
    outputs:
      high: ${{ steps.generator.outputs.high }}
      low: ${{ steps.generator.outputs.low }}
    steps:
      - name: Generate random number between 0-9
        id: generator
        run: |
          num=$((RANDOM % 10))
          echo "The number generated is: $num"

          if [ "$num" -ge 5 ]; then
            echo "high=$num" >> $GITHUB_OUTPUT
          else
            echo "low=$num" >> $GITHUB_OUTPUT
          fi

      - name: HIGH steps
        if: ${{ steps.generator.outputs.high }}
        run: |
          echo "The number is very high: ${{ steps.generator.outputs.high }}"

      - name: low steps
        if: ${{ steps.generator.outputs.low }}
        run: |
          echo "The number is low: ${{ steps.generator.outputs.low }}"

  high:       
    needs: selection # this can be a list (e.g. needs: [jobA, jobB]
    if: ${{ needs.selection.outputs.high }}
    runs-on: ubuntu-latest
    steps:
      - name: See number
        run: |
          echo "The generated number is HIGH: ${{ needs.selection.outputs.high }}"

  low:       
    needs: selection # this can be a list (e.g. needs: [jobA, jobB]
    if: ${{ needs.selection.outputs.low }}
    runs-on: ubuntu-latest
    steps:
      - name: See number
        run: |
          echo "The generated number is low: ${{ needs.selection.outputs.low }}"
      
