name: Set PR Title

on:
  pull_request:
    branches: [main]
    types: 
      - opened
      - synchronize

jobs:
  set-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Details and get PR title
        id: get_pr_title
        run: |
          echo "Owner=${{ github.repository_owner }}"
          echo "Repository=${{ github.repository }}"
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT

      - name: Rename PR title IF test_me is missing
        if: contains(steps.get_pr_title.outputs.PR_TITLE, 'test_me') == false
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Fetch the PR number
          PR_NUMBER=${{ github.event.pull_request.number }}

          # Define the new title
          NEW_TITLE="${{ steps.get_pr_title.outputs.PR_TITLE }} test_me"
          
          gh pr edit $PR_NUMBER --title "$NEW_TITLE"
