name: Set PR Title

on:
  pull_request:
    branches: [main]
    types: 
      - opened
      - synchronize

jobs:
  set-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Details and get PR title
        id: get_pr_title
        run: |
          echo "Owner=${{ github.repository_owner }}"
          echo "Repository=${{ github.repository }}"
          echo "pr_title=${{ github.event.pull_request.title }}"
          echo "PR_TITLE=$pr_title" >> $GITHUB_OUTPUT
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV

      - name: Rename PR title IF test_me is missing
        if: contains(steps.get_pr_title.outputs.PR_TITLE, 'test_me') == false
        run: |
          echo "Running this step..."
