name: Set PR Title

on:
  pull_request:
    branches: [main]
    types: [opened]

jobs:
  set-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: |
          echo "Owner=${{ github.repository_owner }}"
          echo "Repository=${{ github.repository }}"
          echo "PR title=${{ github.event.pull_request.title }}"
      
