# Reference: https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28
name: Secrets

on: workflow_dispatch

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python modules
        run: |
          pip install requests pynacl
        
      - name: Send secrets
        run: |          
          repos=(
            "try-ghactions-sharedwf"
          )
          
          chmod 755 scripts/*.py

          for repo in "${repos[@]}"; do            
            python scripts/secrets.py "${{ secrets.GH_TOKEN }}" "$repo"
          done
