name: Shared Workflow

on: 
  push:
  workflow_dispatch:

jobs:
  test:
    # your-org/repo/.github/workflows/wf-name.yaml@main
    uses: lightzane/try-ghactions-sharedwf/.github/workflows/shared.yaml@v1
      with:
        example_input: "Hello world!"

